### ISSUE TITLE
pfsense question

### ISSUE THREAD

**Issue by blackyellowred** [bntjah/lancache#102]
Hi,
If I were to not use unbound you guys provide and use unbound provided by my firewall pfsense, can I just make do with host overrides to appropriate ip address?

Thanks

**Comment by n0xlf** [comment]
The answer is yes, and I can save you a lot of typing!

Running this at the Intel LANFest Colorado now with these on PFSense:

`address=/client-download.steampowered.com/10.10.0.51
address=/content1.steampowered.com/10.10.0.51
address=/content2.steampowered.com/10.10.0.51
address=/content3.steampowered.com/10.10.0.51
address=/content4.steampowered.com/10.10.0.51
address=/content5.steampowered.com/10.10.0.51
address=/content6.steampowered.com/10.10.0.51
address=/content7.steampowered.com/10.10.0.51
address=/content8.steampowered.com/10.10.0.51
address=/cs.steampowered.com/10.10.0.51
address=/edge.steam-dns.top.comcast.net/10.10.0.51
address=/edge.steam-dns-2.top.comcast.net/10.10.0.51
address=/clientconfig.akamai.steamtransparent.com/10.10.0.51
address=/hsar.steampowered.comedgesuite.net/10.10.0.51
address=/steamcontent.com/10.10.0.51
address=/edgecast.steamstatic.com/10.10.0.51
address=/steampipe.akamaized.net/10.10.0.51
address=/steam.apac.qtlglb.com/10.10.0.51
address=/steam.apac.qtlglb.commwcloudcdn.com/10.10.0.51
address=/cdn1-sea1.valve.net/10.10.0.51
address=/cdn2-sea1.valve.net/10.10.0.51
address=/l3cdn.riotgames.com/10.10.0.52
address=/riotgamespatcher-a.akamaihd.net/10.10.0.52
address=/riotgamespatcher-a.akamaihd.netedgesuite.net/10.10.0.52
address=/riotgamespatcher-b.akamaihd.net/10.10.0.52
address=/riotgamespatcher-b.akamaihd.netedgesuite.net/10.10.0.52
address=/worldwide.l3cdn.riotgames.com/10.10.0.52
address=/dist.blizzard.com/10.10.0.53
address=/llnw.blizzard.com/10.10.0.53
address=/level3.blizzard.com/10.10.0.53
address=/dist.blizzard.comedgesuite.net/10.10.0.53
address=/blzddist1-a.akamaihd.net/10.10.0.53
address=/blzddist2-a.akamaihd.net/10.10.0.53
address=/blzddist1-b.akamaihd.net/10.10.0.53
address=/blzddist2-b.akamaihd.net/10.10.0.53
address=/blzddist3-a.akamaihd.net/10.10.0.53
address=/blzddist3-b.akamaihd.net/10.10.0.53
address=/blizzard.vo.llnwd.net/10.10.0.53
address=/edge.blizzard.top.comcast.net/10.10.0.53
address=/edgecast.blizzard.com/10.10.0.53
address=/nydus.battle.net/10.10.0.53
address=/hirez.http.internapcdn.net/10.10.0.54
address=/akamai.cdn.ea.com/10.10.0.55
address=/download.origin.com/10.10.0.55
address=/origin-a.akamaihd.net/10.10.0.55
address=/lvlt.cdn.ea.com/10.10.0.55
address=/origin-b.akamaihd.net/10.10.0.55
address=/river.data.ea.com/10.10.0.55
address=/pls.patch.station.sony.com/10.10.0.56
address=/gs2.ww.prod.dl.playstation.net/10.10.0.56
address=/gs2.sonycoment.loris-e.llnwd.net/10.10.0.56
address=/download.microsoft.com/10.10.0.57
address=/update.microsoft.comakadns.net/10.10.0.57
address=/update.microsoft.comnsatc.net/10.10.0.57
address=/windowsupdate.com/10.10.0.57
address=/update.microsoft.com/10.10.0.57
address=/windowsupdate.microsoft.com/10.10.0.57
address=/msxbassets.loris.llnwd.net/10.10.0.57
address=/hwcdn.net/10.10.0.57
address=/assets1.xboxlive.com/10.10.0.57
address=/assets2.xboxlive.com/10.10.0.57
address=/xboxone.loris.llnwd.net/10.10.0.57
address=/xboxone.vo.llnwd.net/10.10.0.57
address=/images-eds.xboxlive.com/10.10.0.57
address=/xbox-mbr.xboxlive.com/10.10.0.57
address=/assets1.xboxlive.comnsatc.net/10.10.0.57
address=/fullproduct.download.microsoft.com/10.10.0.57
address=/dlassets.xboxlive.com/10.10.0.57
address=/tlu.dl.delivery.mp.microsoft.com/10.10.0.57
address=/officecdn.microsoft.comedgesuite.net/10.10.0.57
address=/lcy.llnw.net/10.10.0.57
address=/lon.llnw.net/10.10.0.57
address=/patch.tera.enmasse-game.com/10.10.0.58
address=/patch.closers.enmasse-game.com/10.10.0.58
address=/download.enmasse.com/10.10.0.58
address=/cdn.gog.com/10.10.0.59
address=/wpc.11df.deltacdn.net/10.10.0.59
address=/11df-eu-lb.wpc.edgecastcdn.net/10.10.0.59
address=/11df-eu-lb.apr-11df.edgecastdns.net/10.10.0.59
address=/assetcdn.101.arenanetworks.com/10.10.0.60
address=/assetcdn.102.arenanetworks.com/10.10.0.60
address=/assetcdn.103.arenanetworks.com/10.10.0.60
address=/live.patcher.bladeandsoul.com/10.10.0.60
address=/wg.gcdn.co./10.10.0.61
address=/wargaming.netedgesuite.net/10.10.0.61
address=/wgusst-na.wargaming.net/10.10.0.61
address=/wgusst-eu.wargaming.net/10.10.0.61
address=/update-v4r4h10x.worldofwarships.com/10.10.0.61
address=/static-sguscs.worldofwarships.com/10.10.0.61
address=/dl2.wargaming.net/10.10.0.61
address=/dl-wows-ak.wargaming.net/10.10.0.61
address=/dl-wows-cdx.wargaming.net/10.10.0.61
address=/dl-wows-gc.wargaming.net/10.10.0.61
address=/dl-wot-cdx.wargaming.net/10.10.0.61
address=/dl-wot-gc.wargaming.net/10.10.0.61
address=/dl-wowp-cdx.wargaming.net/10.10.0.61
address=/dl-wowp-gc.wargaming.net/10.10.0.61
address=/wguswgc-na.wargaming.net/10.10.0.61
address=/wguscs-wotcom.wargaming.net/10.10.0.61
address=/wguscs-twaeu.wargaming.net/10.10.0.61
address=/dl-twa-gc.wargaming.net/10.10.0.61
address=/dht.transmissionbt.com/127.0.0.1
address=/router.utorrent.com/127.0.0.1
address=/router.bitcomet.com/127.0.0.1
address=/dht.aelitis.com/127.0.0.1
address=/torrents.worldoftanks.ru/127.0.0.1
address=/cdn.ubi.com/10.10.0.62
address=/mzstatic.com/10.10.0.63
address=/swcdn.apple.com/10.10.0.63
address=/itunes-apple.com/10.10.0.63
address=/swscan.apple.com/10.10.0.63
address=/osxapps.itunes.apple.com/10.10.0.63
address=/aa-update.dyn.triongames.com/10.10.0.64
address=/patcher.elderscrollsonline.com/10.10.0.65
address=/content.warframe.com/10.10.0.66
address=/akamai-gamecdn.blackdesertonline.com/10.10.0.67`

The only additions to the normal config are the Comcast entries, which you may not need - If you do, the config gets a bit more complicated because for Steam you need to have sniproxy using a DNS server that redirects all of the Steam related entries above to 127.0.0.1, otherwise clients will get the content via Comcast's servers using SSL, through sniproxy.  It's not a great way of doing it, but eventually the Steam client times out on the SSL request and then tries the valve servers directly, which can be cached.

**Comment by blackyellowred** [comment]
yes this is unbound config right? Can this be done with unbound? just by using the config the config provided?

**Comment by n0xlf** [comment]
It could - What I pasted is what you would put in the "Custom options" section in PFSense when you are using dnsmasq, so either way...
