### ISSUE TITLE
New CDN for Blizzar

### ISSUE THREAD

**Issue by fsalazar1977** [bntjah/lancache#18]
Hi, there is a new CDN for blizzard: level3.blizzard.com (I confirmed using wireshark)
I am using a slice_module based configuration for blizzard, I am having some problems downloading World Of Warcraft (all other blizzard games works fine). When I disable this new CDN the game (WOW) downloads just fine, but a portion is downloaded from this CDN and is not cached. Have you tried this new CDN with your configuration? how does it works? Do you recommend using slices for blizzard? for witch games are you using slices?
Thanks for your work and help, I will be trying your setup soon :)
regards
Freddy

**Comment by bntjah** [comment]
Hey Freddy, haven't seen the new CDN yet as I don't play WoW atm...
I didn't get around to testing it yet, since I had a small lan this weekend.

I have slices installed but from the top of my head I can't say wich games are using it and wich aren't but normally the entire configs that myself, @nexusofdoom & @imac2009  are using should be found in here...

I will try and test the new CDN out this week and get back to you hopefully with a solution ;-)

Regards,

Geoffrey "bn_"

**Comment by nexusofdoom** [comment]
address=/blzddist1-a.akamaihd.net/
address=/blzddist2-a.akamaihd.net/
address=/.level3.blizzard.com/

I am using this for my dns settings

I will have to try , last time I did wow was about 4-6 months ago




<http://www.discoverpc.net>
Travus Elm - Support Specialist
travus@discoverpc.net discoverpc.NET <http://discoverpc.net/>, 1402 Tower
Ave., Superior, WI 54880
Local: (715) 398-6767 ::: Toll-free: (800) 721-1350
Mobile: (218) 260-1940 ::: Fax: (866) 704-3660
*Follow or like us on **Google+*
<https://plus.google.com/111445774308955992766/about?gl=us&hl=en>*, **Facebook
<http://www.facebook.com/pages/discoverpcNET-Computer-Solutions-Center/35471145348>,
**LinkedIn
<https://www.linkedin.com/in/travus-elm-73842268?trk=nav_responsive_tab_profile>*

PRIVILEGED AND CONFIDENTIAL COMMUNICATION This e-mail transmission, and any
documents, files or previous e-mail messages attached to it, may contain
confidential information that is legally privileged. If you are not the
intended recipient or a person responsible for delivering it to the
intended recipient, you are hereby notified that any disclosure, copying,
distribution or use of any of the information contained in or attached to
this transmission is STRICTLY PROHIBITED. If you have received this
transmission in error, please: (1) immediately notify me by reply e-mail,
or by collect telephone call; and (2) destroy the original transmission and
its attachments without reading or saving in any manner
.

**Comment by nexusofdoom** [comment]
downloading wow on my computer about 13gb left but its playable so will let
you know once it gets done downloading.


<http://www.discoverpc.net>
Travus Elm - Support Specialist
travus@discoverpc.net discoverpc.NET <http://discoverpc.net/>, 1402 Tower
Ave., Superior, WI 54880
Local: (715) 398-6767 ::: Toll-free: (800) 721-1350
Mobile: (218) 260-1940 ::: Fax: (866) 704-3660
*Follow or like us on **Google+*
<https://plus.google.com/111445774308955992766/about?gl=us&hl=en>*, **Facebook
<http://www.facebook.com/pages/discoverpcNET-Computer-Solutions-Center/35471145348>,
**LinkedIn
<https://www.linkedin.com/in/travus-elm-73842268?trk=nav_responsive_tab_profile>*

PRIVILEGED AND CONFIDENTIAL COMMUNICATION This e-mail transmission, and any
documents, files or previous e-mail messages attached to it, may contain
confidential information that is legally privileged. If you are not the
intended recipient or a person responsible for delivering it to the
intended recipient, you are hereby notified that any disclosure, copying,
distribution or use of any of the information contained in or attached to
this transmission is STRICTLY PROHIBITED. If you have received this
transmission in error, please: (1) immediately notify me by reply e-mail,
or by collect telephone call; and (2) destroy the original transmission and
its attachments without reading or saving in any manner
.

**Comment by nexusofdoom** [comment]
Wow download worked for me.no issues

**Comment by nexusofdoom** [comment]
getting this 
[error] upstream timed out (110: Connection timed out) while reading response header from upstream,

should I try this ?

http://stackoverflow.com/questions/28347184/upstream-timed-out-110-connection-timed-out-for-static-content


down vote
accepted
OK, I didn't like reading manuals, but to answer my question:

nginx close upstream connection after request

solved it. So what was the problem: I've configured upstream to use keepalive but Nginx doc suggests to set following options in proxy location:

    proxy_http_version 1.1;
    proxy_set_header Connection "";
That's it and thousand of TIME_WAIT connections in backend are gone, there are only round about 150 now instead of 30-40k.

**Comment by nexusofdoom** [comment]
updated my config for blizzard 

address=/lancache-blizzard.localdomain/10.0.4.24
address=/dist.blizzard.com.edgesuite.net/10.0.4.24
address=/llnw.blizzard.com/10.0.4.24
address=/dist.blizzard.com/10.0.4.24
address=/blzddist1-a.akamaihd.net/10.0.4.24
address=/blzddist1-b.akamaihd.net/10.0.4.24
address=/blzddist2-a.akamaihd.net/10.0.4.24
address=/blzddist2-b.akamaihd.net/10.0.4.24
