### ISSUE TITLE
Steam Cache Not serve from lancache

### ISSUE THREAD

**Issue by saambd** [bntjah/lancache#56]
steam download some games from this ip 58.26.7.212. please help us to update this ip unbound dns ruls or find out this ip dns http address.

**Comment by travispk** [comment]
That IP is not a Valve IP, it is registered to the below...   Maybe it's an ISP caching server?  I've had a similar issue with Cox, they HTTP redirect requests with a 301 to their cache servers with a direct IP and it breaks LANCache because the clients go directly to that IP instead of the DNS addresses we have overridden with Unbound.  I had to have them whitelist me and my event IP's from their cache.

58.26.7.212
Registrant
MY
UNITEM SDN BHD
KUALA LUMPUR
Telekom Malaysia

**Comment by saambd** [comment]
How to i'm doing that please help me.

**Comment by saambd** [comment]
Found the solution bellow the new cdn list for "58.26.7.212" this ip.

local-zone: "steam.apac.qtlglb.com." redirect
local-data: "steam.apac.qtlglb.com. 600 IN A lc-host-steam"
local-zone: "steam.apac.qtlglb.com.mwcloudcdn.com." redirect
local-data: "steam.apac.qtlglb.com.mwcloudcdn.com. 600 IN A lc-host-steam"

Its working now good. :)
