### ISSUE TITLE
Support for GLYPH Client?

### ISSUE THREAD

**Issue by nexusofdoom** [bntjah/lancache#59]
dns name  "aa-update.dyn.triongames.com"

**Comment by brgerig** [comment]
aa-update works for archeage, and only archeage.

Correct DNS entry should by "dyn.triongames.com" as they use various subdomains of that for each of their games. Also, I've occasionally seen "update03.triongames.com"

Those two DNS entries have made it so that every (free, at least) Glyph game gets cached for me.

**Comment by nexusofdoom** [comment]
going to close this one since we have more notes on #63
