### ISSUE TITLE
Microsoft: proxy_cache_lock settings

### ISSUE THREAD

**Issue by ilumos** [bntjah/lancache#95]
Hi there!

Reading through your issue on Windows update problems (#37) saved us at an event a few weeks ago.

I'm interested to know what Windows update quirks require these settings:

```
proxy_cache_lock on;
proxy_cache_lock_timeout 0s;
proxy_cache_lock_age 3600s;
```

Help me understand what's going on here. To me these lines say:

- `proxy_cache_lock on` - Only allow one request at a time to populate a new cache element
- `proxy_cache_lock_timeout 0s` - If there's already one request populating a cache element when another request for the same element is received, and 0s has passed, bypass the cache for this second request and do not cache it
- `proxy_cache_lock_age 3600s` - If the request that is populating a new cache element has not completed after 1 hour, one further request may be passed to the proxied server

The combined effect of these lines seems to be _"any clients that request the same chunk of a Windows update file before it's downloaded into the cache will bypass the cache and the response will not be cached"_. If this is correct, it seems unlikely this condition would happen often, but wouldn't it be better for it to not happen at all, as with the other caches?

What's the reasoning behind these config lines? 

Many thanks! 😀

**Comment by nexusofdoom** [comment]
The time out should have a higher value. Not just 0

When enabled, only one request at a time will be allowed to populate a new
cache element identified according to the proxy_cache_key
<http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_cache_key>
directive
by passing a request to a proxied server. Other requests of the same cache
element will either wait for a response to appear in the cache or the cache
lock for this element to be released, up to the time set by the
proxy_cache_lock_timeout
<http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_cache_lock_timeout>
 directive.


We can work on either 40 or 50 Windows machines at a time and we want some
limits on how many requests are going across the internet connection and
wait for the 206 partial cash to pull from to reduce Jitter for a VoIP
system we also use the ip-based vs hostname to limit specific updates from
Windows to a 40 megabit Max download speed rules are applied in our
firewall otherwise with no settings 40 or 50 machines with saturate our
internet connection all pulling down Windows updates at the same time.

A good example is when we had the fall creative update for windows it was
pulling a hundred percent our ISP bandwidth with nothing left to spare.

When I get to the office I can get our current config and attach here. Some
time Monday.

**Comment by ilumos** [comment]
> The time out should have a higher value. Not just 0

It's currently set to 0 in this repo:

https://github.com/bntjah/lancache/blob/master/conf/vhosts-enabled/lancache-microsoft.conf#L13

Deliberate or mistake?

**Comment by nexusofdoom** [comment]
Depends on how long it takes to download the bigger updates and how fast
the internet is. Not sure I have to look back at notes zero might be a
default setting. An hour setting should be enough time to download most of
the updates again depending on how fast the internet connection is.

**Comment by ilumos** [comment]
Ok great, very useful and informative, thank you!

Should [this config file](https://github.com/bntjah/lancache/blob/master/conf/vhosts-enabled/lancache-microsoft.conf#L13) be updated to a sensible default in that case?

**Comment by nexusofdoom** [comment]
it is set to 320 sec. all done.
